# Generated by Django 4.2.2 on 2023-06-18 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('image', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Database',
        ),
    ]
